### PR TITLE
odroid/xu4: bump kernel to 4.14.165, sudo mount when installing to sd

### PR DESCRIPTION
**Pull request by matrob**
These changes were successfully tested on my Odroid HC2.

### CODE REVIEW

**Comment by paralin** [comment]
Previously I had issues where skiff wouldn't boot with the newer kernel versions from odroid, probably because the zimage was too big to fit in the boot sector in memory. Did you test this? If so, I'll test + merge as well.

**Comment by matrob** [comment]
In addition to these changes, the following functions have been successfully tested on my Odroid HC2:

- Docker
- Ethernet

**Comment by paralin** [comment]
@matrob Very nice, OK I will build and test on my HC2s and XU4s here today and merge once that's done.

**Comment by paralin** [comment]
I merged your commits to "next". When sending PRs, please make a separate branch to send specifically the commits you want merged, so that I can rebase and push the rebased branch back to your repo and the PR will close automatically as merged rather than closed.

Thanks!

**Comment by paralin** [comment]
Merged most of it to master, still testing the kernel bump for the xu4.

**Pull request closed without merging**
