### PR TITLE
WIP: add patch to increase Allwinner A20 SATA write performance

### PR DESCRIPTION
**Pull request by matrob**
A test is still pending on the following platform Banana Pro.

### CODE REVIEW

**Comment by paralin** [comment]
I'll try to test locally soon

**Comment by paralin** [comment]
FYI: best way to apply a patch:

first clone the repository (in this case Linux) and check out the same commit Skiff uses

Then, apply the patch e-mail with `git am patch-email.patch`

Make sure the commit is formatted correctly, etc, 

Then: `git format-patch HEAD~1`

It will create the 000-add-patch-to-increase-.patch file, which you can copy into the kernel_patches directory in Skiff directly.

**Comment by matrob** [comment]
Thank you for pointing that out.

I updated the patch to a newer version.
https://patchwork.kernel.org/patch/10941009/

**Comment by paralin** [comment]
Is this all ready to go?

**Comment by matrob** [comment]
I can finally test the changes on Monday.

**Comment by paralin** [comment]
Great - let's test it against 2019.05 as well :)

**Comment by paralin** [comment]
Merged and included in master now

**Pull request closed without merging**
